12-rails-forms-crud/zodi_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :signs #, only: [:index, :show, :new, :create, :edit, :update]

  # get '/signs', to: "signs#index", as: "signs"
  # get '/signs/new', to: "signs#new", as: "new_sign"
  # get '/signs/:id', to: "signs#show", as: "sign"
  # post '/signs', to: "signs#create"
  # get '/signs/:id/edit', to: "signs#edit", as: "edit_sign"

end

12-rails-forms-crud/zodi_app/app/models/sign.rb
class Sign < ApplicationRecord
end

12-rails-forms-crud/zodi_app/app/controllers/signs_controller.rb
class SignsController < ApplicationController

  def index 
    @signs = Sign.all
    # render :index
  end 

  def show 
    @sign = Sign.find(params[:id])
    render :show
  end 

  def new 
    @sign = Sign.new
  end 

  def create 
    sign = Sign.create(sign_params)

    redirect_to sign_path(sign.id) # "/sings/:id"
  end 
  
  def edit 
    @sign = Sign.find(params[:id])
  end 
  
  def update 
    sign = Sign.find(params[:id])
    sign.update(sign_params)
    
    redirect_to sign_path(sign.id) # "/sings/:id"
  end

  private 

  def sign_params
    params.require(:sign).permit(:name, :date, :element, :img_url)
  end 
end

12-rails-forms-crud/zodi_app/app/views/signs/new.html.erb
<h1>Create New Sign</h1>

<%= form_for @sign  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :date %>
  <%= f.text_field :date %>

  <%= f.label :element %>
  <%= f.text_field :element %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>

  <%= f.submit %>
<% end %>

12-rails-forms-crud/zodi_app/app/views/signs/show.html.erb
<h1>Show Page</h1>

<h1><%= @sign.name %></h1>
<p><%= @sign.date %></p>
<p><%= @sign.element %></p>

<%= link_to "INDEX", signs_path %>