16-authentication-authorization/zodi_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :users, only: [:new, :create, :show]
  resources :signs #, only: [:index, :show, :new, :create, :edit, :update]

  patch "/sessions/page_view_reset", to: 'sessions#page_view_reset', as: 'reset_session' 
  delete "/sessions/logout", to: "sessions#logout", as: "logout"
  get "/sessions/new", to: "sessions#new", as: "new_login"
  post "/sessions", to: "sessions#create", as: "login"
  # get '/signs', to: "signs#index", as: "signs"
  # get '/signs/new', to: "signs#new", as: "new_sign"
  # get '/signs/:id', to: "signs#show", as: "sign"
  # post '/signs', to: "signs#create"
  # get '/signs/:id/edit', to: "signs#edit", as: "edit_sign"

end

16-authentication-authorization/zodi_app/app/models/sign.rb
class Sign < ApplicationRecord
  has_many :users

  # def name_plus_element
  #   "#{self.name} - #{self.element}"
  # end 
end

16-authentication-authorization/zodi_app/app/models/user.rb
class User < ApplicationRecord
  belongs_to :sign

  validates :name, uniqueness: { case_sensitive: false }
  validates :name, presence: true
  validates :age, numericality: { greater_than: 17 }

  validate :name_can_not_be_greg
  has_secure_password

  def name_can_not_be_greg
    if self.name && self.name == 'scott'
      self.errors.add(:name, 'can not be me uncle')
    end  
  end 


  # def password=(secret)
  #   hash_pass = BCrypt::Password.create(secret)
  #   self.rando_password = hash_pass 
  #   self.password_digest = hash_pass
  # end

  # def password
  # end 
end

16-authentication-authorization/zodi_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :get_user
  before_action :auth_user

  def get_user
    # @current_user = User.find(session[:user_id])
    @current_user = User.find_by(id: session[:user_id])
  end 


  def auth_user
    if @current_user
      # Continue on into app
    else 
      redirect_to new_user_path
    end  
  end 

end

16-authentication-authorization/zodi_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :auth_user, only: [:new, :create]

  def page_view_reset
    session[:view_count] = 0 

    # redirect_to sing_path(sign)
    redirect_back fallback_location: signs_path
  end 

  def logout
    # session[:id] = nil 
    session.delete(:user_id)
  end 

  def new 
  end 

  def create 
    user = User.find_by(name: params[:session][:name])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id

      redirect_to signs_path
    else
      flash[:error] = "Username or Password is Incorrect"
      redirect_to new_login_path
    end  
  end 
 
end

16-authentication-authorization/zodi_app/app/controllers/signs_controller.rb
class SignsController < ApplicationController
  before_action :find_sign, only: [:show, :edit, :update, :destroy] 

  def index 
    @signs = Sign.all
    # render :index
  end 

  def show 
    if session[:view_count]
      session[:view_count] = session[:view_count] + 1 
    else 
      session[:view_count] = 1
    end 
    # @sign = Sign.find(params[:id])
    # render :show
  end 

  def new 
    @sign = Sign.new
  end 

  def create 
    sign = Sign.create(sign_params)

    redirect_to sign_path(sign.id) # "/sings/:id"
  end 
  
  def edit 
    # @sign = Sign.find(params[:id])
  end 
  
  def update 
    # @sign = Sign.find(params[:id])
    @sign.update(sign_params)
    
    redirect_to sign_path(@sign.id) # "/sings/:id"
  end

  def destroy 
    # @sign = Sign.find(params[:id])
    @sign.destroy 

    redirect_to signs_path
  end 

  private 

  def sign_params
    params.require(:sign).permit(:name, :date, :element, :img_url)
  end 

  def find_sign
    @sign = Sign.find(params[:id])
  end

end

16-authentication-authorization/zodi_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :auth_user, only: [:new, :create]

  def new 
    @user = User.new

    @signs = Sign.all
  end 

  def show 
    @user = User.find(params[:id])

    if @user == @current_user
      render :show 
    else
      flash[:error] = "can only view your own profile page" 
      redirect_to user_path(@current_user)
    end 
  end 

  def create 
    user = User.create(user_params)
    # user = User.new(user_params)

    # if user.save
    if user.valid? 
     session[:user_id] = user.id
     redirect_to sign_path(user.sign_id)
    else
      flash[:user_errors] = user.errors.full_messages

      redirect_to new_user_path 
    end 

  end 

  private 

  def user_params
    params.require(:user).permit(:name, :age, :birthday, :img_url, :sign_id, :password)
  end 



end

16-authentication-authorization/zodi_app/app/helpers/application_helper.rb
module ApplicationHelper
end

16-authentication-authorization/zodi_app/app/helpers/signs_helper.rb
module SignsHelper
end

16-authentication-authorization/zodi_app/app/helpers/users_helper.rb
module UsersHelper
end

16-authentication-authorization/zodi_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZodiApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <ul>
        <li><%= link_to 'User Home', users_path %></li>
        <li><%= link_to 'Sign Home', signs_path %></li>
        <li><%= link_to 'New Sign', new_sign_path %></li>

        <% if @current_user %>
          <li class='right'> Welcome <%=  @current_user.name %></li>                    
          <li class='right'><%= link_to "Log-Out", logout_path, method: :delete %></li>
        <% else %>
          <li class='right'><%= link_to 'Sign-up', new_user_path %></li>
          <li class='right'><%= link_to 'Login', new_login_path %></li>
        <% end %>
      </ul>

    <%= yield %>
  </body>
</html>

16-authentication-authorization/zodi_app/app/views/signs/_beef.html.erb
<%= form_for @sign  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :date %>
  <%= f.text_field :date %>

  <%= f.label :element %>
  <%= f.text_field :element %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>

  <%= f.submit %>
<% end %>

16-authentication-authorization/zodi_app/app/views/signs/edit.html.erb
<h1>Edit This Sign</h1>


<%= render 'beef' %>

16-authentication-authorization/zodi_app/app/views/signs/index.html.erb
<h1>SINGS!!!</h1>

<% @signs.each do |sign| %>
  <p><%= link_to sign.name, sign %></p>
<% end %>

16-authentication-authorization/zodi_app/app/views/signs/new.html.erb
<h1>Create New Sign</h1>

<%= render 'beef' %>

16-authentication-authorization/zodi_app/app/views/signs/show.html.erb
<% if session[:view_count] <= 3 %>
  <h1>YOU HAVE <%= 3 - session[:view_count] %> Page Views Left</h1>

  <h1>Show Page</h1>

  <h1><%= @sign.name %></h1>
  <p><%= @sign.date %></p>
  <p><%= @sign.element %></p>

  <h3>All Users With Sign</h3>

  <% @sign.users.each do |user|  %>
    <p><%= user.name %></p>
  <% end %>


  <%= link_to "INDEX", signs_path %>
  <br>
                      <%# /signs/:id/edit %>
  <%= link_to "EDIT",  edit_sign_path(@sign) %>

                        <%# /signs/:id %>
  <%= button_to "DELETE", sign_path(@sign), method: :delete %>
<% else %>

  <h1>SHOW ADD</h1>
  <iframe width="946" height="532" src="https://www.youtube.com/embed/lHdLRrUocOA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  <%= button_to "I SUPER PROMISE I WATCHED THIS AD", reset_session_path, method: :patch %>

<% end %>

16-authentication-authorization/zodi_app/app/views/users/new.html.erb
<h1>CREATE NEW USER</h1>

<% if flash[:user_errors] %>
  <% flash[:user_errors].each do |error| %>
    <p style='color: red;'><%= error %></p>
  <% end %>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :password %>
  <%= f.text_field :password %>

  <%= f.label :birthday %>
  <%= f.text_field :birthday %>

  <%= f.label :age %>
  <%= f.number_field :age %>

  <%= f.label :img_url %>
  <%= f.text_field :img_url %>

  <%= f.label :sign_id %>
  <%= f.collection_select :sign_id, @signs, :id, :name  %>

  <%= f.submit %>
  
<% end %>

16-authentication-authorization/zodi_app/app/views/users/show.html.erb
<h1>USER SHOW</h1>
<% if flash[:error] %>
  <h1 style="color: red;"><%= flash[:error] %></h1>
<% end %>


<h1><%= @user.name %></h1>